### PR TITLE
fix find next lesson

### LINKED ISSUE #140: [PE-D] Long text flowing out of the class boxes
A minor flaw in GUI, long text flows out of the boxes:

-------------
Labels: `severity.VeryLow` `type.FunctionalityBug`
original: syinyichen/ped#9

### LINKED ISSUE #166: [PE-D] Inaccurate Error Messages for Commands with Multiple Patameters Needed
In command that  needs a lot of parameters, such as add class, when I type in 

class add /code MA1521 /type /at Friday 12:00 12:00 /venue i3-Aud

It says that 'The type must be .....', but it is better if the error message is 'The type cannot be empty'

-------------
Labels: `severity.Low` `type.FunctionalityBug`
original: agnesnatasya/ped#4

### PR DESCRIPTION
**Pull request by heidicrq**
module tab will show tasks and facils when find next lesson command is executed

### CODE REVIEW

File: src/main/java/seedu/address/logic/commands/lesson/LessonFindCommand.java [hunk 1]
```diff
@@ -41,6 +43,7 @@ public CommandResult execute(Model model) {
             } else {
                 result = "Next lesson:\n" + lesson.toString();
             }
+            new ModuleViewCommand(lesson.getModuleCode()).execute(model);
```
Comment (zixinn) [inline src/main/java/seedu/address/logic/commands/lesson/LessonFindCommand.java]: I think will have null pointer exception when there is no next class (e.g. when the class list is empty).

Comment (heidicrq) [reply src/main/java/seedu/address/logic/commands/lesson/LessonFindCommand.java]: Yea, I will shift that thing into the else clause soon!
