### PR TITLE
Fix Mock PE issues, and UG

### LINKED ISSUE #160: [PE-D] Date Validation
There is a weird behaviour where you accept the date 30 of month 2, which never happens.

Also, the 'day' keyword is misleading, it should be 'date' instead of 'day', 'day' makes people think that it should be '/day monday', but you mentioned that it is invalid in the user guide, so it is quite confusing

-------------
Labels: `severity.Medium` `type.FunctionalityBug`
original: agnesnatasya/ped#10

### LINKED ISSUE #162: [PE-D] View after CRUD commands
After doing any CRUD operations, the view is not directed to the recently edited element, which is not favourable for the user. I think it is better to scroll the view to the particular element, and even highlight it or focus on it so we know which one has currently been added, edited, or deleted, etc. 

-------------
Labels: `severity.Low` `type.FunctionalityBug`
original: agnesnatasya/ped#8

### PR DESCRIPTION
**Pull request by dinhnhobao**
Closes #160 
Closes #162

### CODE REVIEW

File: src/main/java/seedu/address/logic/parser/task/TaskSearchCommandParser.java [hunk 1]
```diff
@@ -76,6 +95,82 @@ public TaskSearchCommand parse(String args) throws ParseException {
...
+                }
+            } else if (keywords.containsKey("year")) {
+                if (isOutOfBoundsYear(keywords.get("year"))) {
+                    throw new ParseException(String.format(MESSAGE_INVALID_COMMAND_FORMAT,
+                            TaskSearchCommand.MESSAGE_OUT_OF_BOUNDS_VALUES));
+                }
+            }
+        }
+
+        System.out.println(keywords);
```
Comment (NNpanpan) [inline src/main/java/seedu/address/logic/parser/task/TaskSearchCommandParser.java:173]: Should abstract with methods
Too many nested if-else blocks -> hard to debug + low readability

Alternative flow + method abstract:
`boolean[] has = new boolean[3]; // has[0] = hasDate, has[1] = hasMonth, has[2] = hasYear`
`boolean[] check = new boolean[3];`

`if (has[0]): check[0] = validDate; ` 
`if (has[0] ^ check[0]): throw exception // false means no date or valid date`

`if (has[1]):`
- `if (has[0]): check[1] = checkCompatibleDateMonth;` 
- `else: check[1] = validMonth;`

`if (has[1] ^ check[1]): throw exception // false means no month or valid month`
 
`if (has[2]):`
- `if (has[0] and has[1]): check[2] = leapYearCheck;`
- `else: check[2] = validYear;`

`if (has[2] ^ check[2]): throw exception`

Extra methods: validDate (<= 31 check), validMonth(<= 12), validYear(<= 9999), checkCompatibleDateMonth, leapYearCheck

**Review by NNpanpan — COMMENTED** [review]
Too much nesting

File: src/main/java/seedu/address/logic/parser/task/TaskSearchCommandParser.java (hunk 1 above)
Comment (dinhnhobao) [reply src/main/java/seedu/address/logic/parser/task/TaskSearchCommandParser.java:173]: Can merge, I will try to fix that later. I couldn't think of a better way for the logic as of now, since that is just the rule of how the date works. I have abstracted it out using `final` constants.

Comment (NNpanpan) [reply src/main/java/seedu/address/logic/parser/task/TaskSearchCommandParser.java:173]: The `^` in `has[0] ^ check[0]` just checks if `has[0] != check[0]`

Comment (dinhnhobao) [reply src/main/java/seedu/address/logic/parser/task/TaskSearchCommandParser.java:173]: Thanks, fixing it right now!
